<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Username' => 'Nombre de usuario',
    'Authorization' => 'Autorización',
    'Captcha' => 'Captcha',
    'Check your E-mail for further instructions' => 'Revisa tu correo electrónico por instruccionesa adicionales',
    'Check your e-mail {email} for instructions to activate account' => 'Revisa tu correo electrónico {email} por instrucciones para activar tu cuenta',
    'Confirm' => 'Confirmar',
    'Confirm E-mail' => 'Confirmar Correo electrónico',
    'Continue' => 'Continuar',
    'Could not send confirmation email' => 'No se pudo enviar correo de confirmación',
    'E-mail confirmation for' => 'Correo electrónico de confirmación para',
    'E-mail confirmed' => 'Correo electrónico confirmado',
    'E-mail is invalid' => 'Correo electrónico es invalido',
    'Forgot password ?' => 'Olvidaste la contraseña ?',
    'Incorrect username or password.' => 'Nombre de usuario o contraseña incorrecto',
    'Login' => 'Iniciar sesión',
    'Login has been taken' => 'Usuario ha sido tomado',
    'Password' => 'Contraseña',
    'Password recovery' => 'Recuperar contraseña',
    'Password reset for' => 'Reiniciar la contraseña para',
    'Recover' => 'Recuperar',
    'Register' => 'Registrar',
    'Registration' => 'Registro',
    'Registration - confirm your e-mail' => 'Registro - confirma tu correo electrónico',
    'Remember me' => 'Recordarme',
    'Repeat password' => 'Repetir contraseña',
    'This E-mail already exists' => 'Este Correo electrónico ya existe',
    'Token not found. It may be expired' => 'El Token no se encontro. Pudo haber expirado',
    'Token not found. It may be expired. Try reset password once more' => 'El Token no se encontro. Pudo haber expirado. Intenta reiniciar al contraseña una vez más',
    'Too many attempts' => 'Demasiados intentos',
    'Unable to send message for email provided' => 'No se puede enviar el mensaje al correo electrónico suministrado',
    'You could not login from this IP' => 'No puedes iniciar sesión desde esta IP',
];
